# Generated by Django 3.2 on 2021-04-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectapp', '0003_auto_20210418_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
