# Generated by Django 3.2 on 2021-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectapp', '0002_alter_hero_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='name',
        ),
        migrations.AddField(
            model_name='hero',
            name='invalid_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='max1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='min1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='summation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='valid_entries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
