# Generated by Django 3.2 on 2021-04-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectapp', '0004_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('strength', models.IntegerField(default=10)),
                ('cur', models.IntegerField(default=0)),
            ],
        ),
    ]
